FROM debian:stable-slim

ARG USERNAME=esp32
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update && apt-get install -y \
    locales \
    udev \
    git \
    wget \
    flex \
    bison \
    gperf \
    python3 \
    python3-pip \
    python3-venv \
    cmake \
    ninja-build \
    ccache \
    libffi-dev \
    libssl-dev \
    dfu-util \
    libusb-1.0-0 \
    libglib2.0-0 \
    libpixman-1-0 \
    libsdl2-2.0-0 \
    libslirp0 \
    libgcrypt20 \
    \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN groupadd -g ${GROUP_ID} ${USERNAME} && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash ${USERNAME}

USER ${USERNAME}

WORKDIR /home/${USERNAME}/esp

RUN git clone -b v6.0.1 --recursive https://github.com/espressif/esp-idf.git

WORKDIR /home/${USERNAME}/esp/esp-idf

RUN ./install.sh all

RUN python3 tools/idf_tools.py install qemu-xtensa qemu-riscv32

RUN echo ". /home/${USERNAME}/esp/esp-idf/export.sh" >> /home/${USERNAME}/.profile

